### ISSUE TITLE
Dataset Link

### ISSUE THREAD

**Issue by XixiLiu95** [princetonvisualai/imagenetood#1]
Hi,

Nice work!  I'm curious if it's feasible to prioritize the preparation of the dataset link for downloading.

Many thanks :)

**Comment by black0017** [comment]
+1

**Comment by iceshade000** [comment]
+1

**Comment by yang-william** [comment]
Sorry for missing this issue. The ImageNet-21K subsets is located in imagenetood.txt (contains the classes and image names). Links to ImageNet-21K as well as code for the dataset object has since been added.
